#!/bin/bash

clear
set -e
tabs -2

EXE_NAME="play"
MAIN_FILE="play/play.go"

TEST_TIMEOUT="2s"
BUILD_FLAGS=""
#BUILD_FLAGS=-gcflags -m -ldflags "-s -w"

printUsage() {
	println "Usage:"
	println "\t" "./godo [help]" "\t\t" "# Print usage"
	println "\t" "./godo clean " "\t\t" "# Clean build & Go caches"
	println "\t" "./godo tidy  " "\t\t" "# Tidy Go mod & install packages"
	println "\t" "./godo test  " "\t\t" "# build -> fmt   -> test -> vet"
	println "\t" "./godo dev   " "\t\t" "# fmt   -> test  -> vet  -> dev"
	println "\t" "./godo debug " "\t\t" "# fmt   -> test  -> vet  -> dev (verbose)"
	println "\t" "./godo build " "\t\t" "# clean -> build -> test -> vet"
	println "\t" "./godo commit" "\t\t" "# clean -> fmt -> build -> test -> vet"
}

println() {
	for s in "$@"
	do
		printf "$s"
	done
	printf "\\n"
}

godoClean() {
	println "Cleaning..."
	rm -rf "build/bin" "frontend/dist"
	go clean -cache -testcache
}

godoTidy() {
	println "Tidying..."
	go mod tidy
	npm --prefix "./frontend" install
}

godoFmt() {
	println "Formatting..."
	go fmt ./...
}

godoTest() {
	println "Testing..."
	go test ./... -timeout $TEST_TIMEOUT
}

godoVet() {
	println "Vetting..."
	go vet ./...
}

wailsBuild() {
	println "Building..."
	wails build -v 0
}

wailsDev() {
	println "Dev..."
	wails dev -v 0
}

wailsDebug() {
	println "Dev..."
	wails dev -v 3
}


if [[ "$1" == "" || "$1" == "help" ]]; then
	printUsage
	exit 0
fi

if [[ "$1" == "clean" ]]; then
	godoClean
	exit 0
fi

if [[ "$1" == "tidy" ]]; then
	godoTidy
	exit 0
fi

if [[ "$1" == "test" ]]; then
	wailsBuild
	godoFmt
	godoTest
	godoVet
	exit 0
fi

if [[ "$1" == "dev" ]]; then
	godoFmt
	godoTest
	godoVet
	wailsDev
	exit 0
fi

if [[ "$1" == "debug" ]]; then
	godoFmt
	godoTest
	godoVet
	wailsDebug
	exit 0
fi

if [[ "$1" == "build" ]]; then
	godoClean
	wailsBuild
	godoTest
	godoVet
	exit 0
fi

if [[ "$1" == "commit" ]]; then
	godoClean
	godoFmt
	wailsBuild
	godoTest
	godoVet
	exit 0
fi

println "I don't understand the option '$1'."
printUsage
exit 1
