#!/bin/bash

clear
set -e
tabs -2

EXE_NAME="play"
MAIN_FILE="play/play.go"

TEST_TIMEOUT="2s"
BUILD_FLAGS=""
#BUILD_FLAGS=-gcflags -m -ldflags "-s -w"

printUsage() {
	println "Usage:"
	println "\t" "./godo [help]" "\t\t" "# Print usage"
	println "\t" "./godo clean " "\t\t" "# Clean build & Go caches"
	println "\t" "./godo test  " "\t\t" "# build -> fmt   -> test -> vet"
	println "\t" "./godo dev   " "\t\t" "# fmt   -> test  -> vet  -> dev"
	println "\t" "./godo build " "\t\t" "# clean -> build -> test -> vet"
}

println() {
	for s in "$@"
	do
		printf "$s"
	done
	printf "\\n"
}

goClean() {
	println "Cleaning..."
	rm -rf "build/bin" "frontend/dist"
	go clean -cache -testcache
}

goFmt() {
	println "Formatting..."
	go fmt ./...
}

goTest() {
	println "Testing..."
	go test ./... -timeout $TEST_TIMEOUT
}

goVet() {
	println "Vetting..."
	go vet ./...
}

wailsBuild() {
	println "Building..."
	wails build -v 0
}

wailsDev() {
	println "Dev..."
	wails dev -v 0
}


if [[ "$1" == "" || "$1" == "help" ]]; then
	printUsage
	exit 0
fi

if [[ "$1" == "clean" ]]; then
	goClean
	exit 0
fi

if [[ "$1" == "test" ]]; then
	wailsBuild
	goFmt
	goTest
	goVet
	exit 0
fi

if [[ "$1" == "dev" ]]; then
	goFmt
	goTest
	goVet
	wailsDev
	exit 0
fi

if [[ "$1" == "build" ]]; then
	goClean
	wailsBuild
	goTest
	goVet
	exit 0
fi

println "I don't understand the option '$1'."
printUsage
exit 1
