// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
	return window['go']['main']['App']['AddTask'](arg1)
}

export function CloseDatabase() {
	return window['go']['main']['App']['CloseDatabase']()
}

export function GetFilesInDir(arg1) {
	return window['go']['main']['App']['GetFilesInDir'](arg1)
}

export function OpenDatabase(arg1) {
	return window['go']['main']['App']['OpenDatabase'](arg1)
}
