// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
	return window['go']['main']['App']['AddTask'](arg1)
}

export function CloseDatabase() {
	return window['go']['main']['App']['CloseDatabase']()
}

export function CreateDatabase(arg1) {
	return window['go']['main']['App']['CreateDatabase'](arg1)
}

export function ListFilesInDir(arg1) {
	return window['go']['main']['App']['ListFilesInDir'](arg1)
}

export function OpenDatabase(arg1) {
	return window['go']['main']['App']['OpenDatabase'](arg1)
}

export function ToAbsPath(arg1) {
	return window['go']['main']['App']['ToAbsPath'](arg1)
}
