// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { database } from '../models'

export function AddTask(arg1: database.Task): Promise<void>

export function CloseDatabase(): Promise<void>

export function OpenDatabase(arg1: string): Promise<void>
